### PR TITLE
Does not update the old object of an update event.

### LINKED ISSUE #136: Minor bug: policyserver controller errors as watch enters twice per ClusterAdmissionPolicies deletion
Changes to ClusterAdmissionPolicies such as performing a Delete trigger the watch of policyserver_controller.go twice (or so it seems). This doesn't break the functionality, but makes the operations fail on the second run, printing inocuous, albeit bad looking errors.


## Example 1
Instantiate an ClusterAdmissionPolicy into the default PolicyServer. Wait for it to be `active`. Then delete it. Notice that there is an error:
1. "the object has been modified; please apply your changes to the latest version and try again".

The policy gets `Delete`d. The change in the object triggers the watch in policyserver_controller.go, exiting through https://github.com/viccuad/kubewarden-controller/blob/a0b9e9397b0d8f66ac17cdebe26ab773a20a4ced/controllers/policies/policyserver_controller.go#L200-L206. No change has been performed in the policy inside the watch, we go through directly to the PolicyServer reconciler loop, that will take care of de-registering the policy webhooks and removing the Finalizer. Still, we get an error.

```
2021-12-10T11:03:16.962Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "12da5674-874c-4ee2-b8dc-534a73bee5da", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmission
Policy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                         
2021-12-10T11:03:16.962Z    INFO    clusteradmissionpolicy-resource    default    {"name": "local-pod-privileged-policy2"}                                                                                                                                                                  
2021-12-10T11:03:16.963Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "12da5674-874c-4ee2-b8dc-534a73bee5da", "allowed": true}                      
2021-12-10T11:03:16.968Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "dcf32249-d38a-457f-b7a5-4e7f1f312f42", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissi
onPolicy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                       
2021-12-10T11:03:16.968Z    INFO    clusteradmissionpolicy-resource    validate create    {"name": "local-pod-privileged-policy2"}                                                                                                                                                          
2021-12-10T11:03:16.968Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "dcf32249-d38a-457f-b7a5-4e7f1f312f42", "allowed": true}                    
2021-12-10T11:03:16.984Z    INFO    controllers.policies.ClusterAdmissionPolicy    policy local-pod-privileged-policy2 pending                                                                                                                                                              
2021-12-10T11:03:17.033Z    INFO    controllers.policies.ClusterAdmissionPolicy    deployment patched    {"policyserver": "/default"}                                                                                                                                                       
2021-12-10T11:03:17.043Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}                                                                                                        
2021-12-10T11:03:22.117Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}                                                                                                        
2021-12-10T11:03:27.213Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}                                                                                                        
2021-12-10T11:03:32.261Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}                                                                                                        
2021-12-10T11:03:37.306Z    INFO    controllers.policies.ClusterAdmissionPolicy    policy local-pod-privileged-policy2 active    {"policyserver": "/default"}                                                                                                                               
2021-12-10T11:03:44.282Z    ERROR    controllers.policies.ClusterAdmissionPolicy    cannot update status of policy local-pod-privileged-policy2    {"error": "failed to update status of ClusterAdmissionPolicy \"&ObjectMeta{Name:local-pod-privileged-policy2,GenerateName:,Namespace:,S
elfLink:,UID:0050cdda-3a62-423f-b804-1566bdc87887,ResourceVersion:7612,Generation:1,CreationTimestamp:2021-12-10 11:03:16 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-confi
guration: {\\\"apiVersion\\\":\\\"policies.kubewarden.io/v1alpha2\\\",\\\"kind\\\":\\\"ClusterAdmissionPolicy\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"local-pod-privileged-policy2\\\"},\\\"spec\\\":{\\\"module\\\":\\\"registry://ghcr.io/kubewarden/policies/psp-ca
pabilities:v0.1.3\\\",\\\"mutating\\\":false,\\\"rules\\\":[{\\\"apiGroups\\\":[\\\"\\\"],\\\"apiVersions\\\":[\\\"v1\\\"],\\\"operations\\\":[\\\"CREATE\\\",\\\"UPDATE\\\"],\\\"resources\\\":[\\\"pods\\\"]}]}}\\n,},OwnerReferences:[]OwnerReference{},Finalizers:[kubewarden],ClusterNa
me:,ManagedFields:[]ManagedFieldsEntry{ManagedFieldsEntry{Manager:kubectl-client-side-apply,Operation:Update,APIVersion:policies.kubewarden.io/v1alpha2,Time:2021-12-10 11:03:16 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{\\\"f:metadata\\\":{\\\"f:annotations\\\":{\\\".\\\":{},\\\"f:kubec
tl.kubernetes.io/last-applied-configuration\\\":{}}},\\\"f:spec\\\":{\\\".\\\":{},\\\"f:module\\\":{},\\\"f:mutating\\\":{},\\\"f:policyServer\\\":{},\\\"f:rules\\\":{}}},Subresource:,},ManagedFieldsEntry{Manager:manager,Operation:Update,APIVersion:policies.kubewarden.io/v1alpha2,Tim
e:2021-12-10 11:03:37 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{\\\"f:status\\\":{\\\".\\\":{},\\\"f:conditions\\\":{\\\".\\\":{},\\\"k:{\\\\\\\"type\\\\\\\":\\\\\\\"PolicyActive\\\\\\\"}\\\":{\\\".\\\":{},\\\"f:lastTransitionTime\\\":{},\\\"f:message\\\":{},\\\"f:reason\\\":{},\\\"f:s
tatus\\\":{},\\\"f:type\\\":{}}},\\\"f:policyStatus\\\":{}}},Subresource:,},},}\", \"Operation cannot be fulfilled on clusteradmissionpolicies.policies.kubewarden.io \\\"local-pod-privileged-policy2\\\": the object has been modified; please apply your changes to the latest version an
d try again\""}                                                                                                                                                                                                                                                                             
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).Update                                                                                                                                                                                                             
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/handler/enqueue_mapped.go:63                                                                                                                                                                                                     
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate                                                                                                                                                                                                                    
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/source/internal/eventsource.go:94                                                                                                                                                                                                
k8s.io/client-go/tools/cache.(*processorListener).run.func1                                                                                                                                                                                                                                 
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:775                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1                                                                                                                                                                                                                                        
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:155                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.BackoffUntil                                                                                                                                                                                                                                              
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:156                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.JitterUntil                                                                                                                                                                                                                                               
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:133                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.Until                                                                                                                                                                                                                                                     
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:90                                                                                                                                                                                                                        
k8s.io/client-go/tools/cache.(*processorListener).run                                                                                                                                                                                                                                       
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:771                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1                                                                                                                                                                                                                                      
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:73                                                                                                                                                                                                                        
2021-12-10T11:03:44.290Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "86791fe2-5d34-4853-9895-3c3c14e94513", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmission
Policy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                         
2021-12-10T11:03:44.290Z    INFO    clusteradmissionpolicy-resource    default    {"name": "local-pod-privileged-policy2"}                                                                                                                                                                  
2021-12-10T11:03:44.291Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "86791fe2-5d34-4853-9895-3c3c14e94513", "allowed": true}                      
2021-12-10T11:03:44.292Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "0f90d2aa-29f9-4dad-b4bf-7449efc8ae85", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissi
onPolicy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                       
2021-12-10T11:03:44.293Z    INFO    clusteradmissionpolicy-resource    validate update    {"name": "local-pod-privileged-policy2"}                                                                                                                                                          
2021-12-10T11:03:44.293Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "0f90d2aa-29f9-4dad-b4bf-7449efc8ae85", "allowed": true}                    
2021-12-10T11:03:44.331Z    INFO    controllers.policies.ClusterAdmissionPolicy    deployment patched    {"policyserver": "/default"}                                                                                                                                                       
2021-12-10T11:03:44.342Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}                                                                                                        
2021-12-10T11:03:44.384Z    INFO    controllers.policies.ClusterAdmissionPolicy    delaying policy registration since policy server is not yet ready    {"policyserver": "/default"}
```

## Example 2
Instantiate a ClusterAdmissionPolicy that specifies an nonexistent PolicyServer. Wait for it to be unschedulable. Then, delete it (with the code from PR https://github.com/kubewarden/kubewarden-controller/pull/135). Notice that there are 2 errors:
1. the object has been modified; please apply your changes to the latest version and try again
2. clusteradmissionpolicies.policies.kubewarden.io \"local-pod-privileged-policy2\" not found

Error 1 seems analogous to example 1. Error 2, after debugging, seems to appear while going through https://github.com/viccuad/kubewarden-controller/blob/a0b9e9397b0d8f66ac17cdebe26ab773a20a4ced/controllers/policies/policyserver_controller.go#L181-L187. There, we are just removing the Finalizer. Which to me indicates that we go once, remove the finalizer, which triggers the watch on policyserver_controller.go *and* the watch of the Kubernetes controller for garbage collecting. The garbage collection happens, fully removing the policy Object from etcd. Our watch goes through, seeing a policy object with DeletionTimestamp and unschedulable, tries to remove the Finalizer, and tada, there's no object. 

```
2021-12-10T11:12:50.704Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "a9979ba0-ec32-4545-abc4-354465cb8196", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmission
Policy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                         
2021-12-10T11:12:50.704Z    INFO    clusteradmissionpolicy-resource    default    {"name": "local-pod-privileged-policy2"}                                                                                                                                                                  
2021-12-10T11:12:50.704Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "a9979ba0-ec32-4545-abc4-354465cb8196", "allowed": true}                      
2021-12-10T11:12:50.712Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "a5c6808b-6df0-419a-a9f8-2d8ad7ba936a", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissi
onPolicy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                       
2021-12-10T11:12:50.712Z    INFO    clusteradmissionpolicy-resource    validate create    {"name": "local-pod-privileged-policy2"}                                                                                                                                                          
2021-12-10T11:12:50.712Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "a5c6808b-6df0-419a-a9f8-2d8ad7ba936a", "allowed": true}                    
2021-12-10T11:12:50.735Z    INFO    controllers.policies.ClusterAdmissionPolicy    policy local-pod-privileged-policy2 cannot be scheduled: no matching PolicyServer                                                                                                                        
2021-12-10T11:13:14.211Z    ERROR    controllers.policies.ClusterAdmissionPolicy    cannot 2 update status of policy local-pod-privileged-policy2    {"error": "failed to update status of ClusterAdmissionPolicy \"&ObjectMeta{Name:local-pod-privileged-policy2,GenerateName:,Namespace:,S
elfLink:,UID:e5a19af1-a595-435e-a2ff-77ecee5d5c4a,ResourceVersion:9211,Generation:1,CreationTimestamp:2021-12-10 11:12:50 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{},Annotations:map[string]string{kubectl.kubernetes.io/last-applied-confi
guration: {\\\"apiVersion\\\":\\\"policies.kubewarden.io/v1alpha2\\\",\\\"kind\\\":\\\"ClusterAdmissionPolicy\\\",\\\"metadata\\\":{\\\"annotations\\\":{},\\\"name\\\":\\\"local-pod-privileged-policy2\\\"},\\\"spec\\\":{\\\"module\\\":\\\"registry://ghcr.io/kubewarden/policies/psp-ca
pabilities:v0.1.3\\\",\\\"mutating\\\":false,\\\"policyServer\\\":\\\"unexistent\\\",\\\"rules\\\":[{\\\"apiGroups\\\":[\\\"\\\"],\\\"apiVersions\\\":[\\\"v1\\\"],\\\"operations\\\":[\\\"CREATE\\\",\\\"UPDATE\\\"],\\\"resources\\\":[\\\"pods\\\"]}]}}\\n,},OwnerReferences:[]OwnerRefer
ence{},Finalizers:[kubewarden],ClusterName:,ManagedFields:[]ManagedFieldsEntry{ManagedFieldsEntry{Manager:kubectl-client-side-apply,Operation:Update,APIVersion:policies.kubewarden.io/v1alpha2,Time:2021-12-10 11:12:50 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{\\\"f:metadata\\\":{\\\"f:a
nnotations\\\":{\\\".\\\":{},\\\"f:kubectl.kubernetes.io/last-applied-configuration\\\":{}}},\\\"f:spec\\\":{\\\".\\\":{},\\\"f:module\\\":{},\\\"f:mutating\\\":{},\\\"f:policyServer\\\":{},\\\"f:rules\\\":{}}},Subresource:,},ManagedFieldsEntry{Manager:manager,Operation:Update,APIVer
sion:policies.kubewarden.io/v1alpha2,Time:2021-12-10 11:12:50 +0000 UTC,FieldsType:FieldsV1,FieldsV1:{\\\"f:status\\\":{\\\".\\\":{},\\\"f:policyStatus\\\":{}}},Subresource:,},},}\", \"Operation cannot be fulfilled on clusteradmissionpolicies.policies.kubewarden.io \\\"local-pod-priv
ileged-policy2\\\": the object has been modified; please apply your changes to the latest version and try again\""}                                                                                                                                                                         
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).Update                                                                                                                                                                                                             
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/handler/enqueue_mapped.go:63                                                                                                                                                                                                     
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnUpdate                                                                                                                                                                                                                    
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/source/internal/eventsource.go:94                                                                                                                                                                                                
k8s.io/client-go/tools/cache.(*processorListener).run.func1                                                                                                                                                                                                                                 
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:775                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1                                                                                                                                                                                                                                        
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:155                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.BackoffUntil                                                                                                                                                                                                                                              
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:156                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.JitterUntil                                                                                                                                                                                                                                               
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:133                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.Until                                                                                                                                                                                                                                                     
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:90                                                                                                                                                                                                                        
k8s.io/client-go/tools/cache.(*processorListener).run                                                                                                                                                                                                                                       
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:771                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1                                                                                                                                                                                                                                      
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:73                                                                                                                                                                                                                        
2021-12-10T11:13:14.211Z    INFO    controllers.policies.ClusterAdmissionPolicy    policy local-pod-privileged-policy2 cannot be scheduled: no matching PolicyServer                                                                                                                        
2021-12-10T11:13:14.214Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "e5ce388e-ec8a-433c-bda9-b7d140402711", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmission
Policy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                         
2021-12-10T11:13:14.214Z    INFO    clusteradmissionpolicy-resource    default    {"name": "local-pod-privileged-policy2"}                                                                                                                                                                  
2021-12-10T11:13:14.214Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/mutate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "e5ce388e-ec8a-433c-bda9-b7d140402711", "allowed": true}                      
2021-12-10T11:13:14.216Z    DEBUG    controller-runtime.webhook.webhooks    received request    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "UID": "b6af84fd-29bc-4647-a077-6892024ac7e3", "kind": "policies.kubewarden.io/v1alpha2, Kind=ClusterAdmissi
onPolicy", "resource": {"group":"policies.kubewarden.io","version":"v1alpha2","resource":"clusteradmissionpolicies"}}                                                                                                                                                                       
2021-12-10T11:13:14.216Z    INFO    clusteradmissionpolicy-resource    validate update    {"name": "local-pod-privileged-policy2"}                                                                                                                                                          
2021-12-10T11:13:14.216Z    DEBUG    controller-runtime.webhook.webhooks    wrote response    {"webhook": "/validate-policies-kubewarden-io-v1alpha2-clusteradmissionpolicy", "code": 200, "reason": "", "UID": "b6af84fd-29bc-4647-a077-6892024ac7e3", "allowed": true}                    
2021-12-10T11:13:14.224Z    ERROR    controllers.policies.ClusterAdmissionPolicy    cannot 1 update status of policy local-pod-privileged-policy2    {"error": "clusteradmissionpolicies.policies.kubewarden.io \"local-pod-privileged-policy2\" not found"}                                
sigs.k8s.io/controller-runtime/pkg/handler.(*enqueueRequestsFromMapFunc).Delete                                                                                                                                                                                                             
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/handler/enqueue_mapped.go:70                                                                                                                                                                                                     
sigs.k8s.io/controller-runtime/pkg/source/internal.EventHandler.OnDelete                                                                                                                                                                                                                    
    /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.0/pkg/source/internal/eventsource.go:137                                                                                                                                                                                               
k8s.io/client-go/tools/cache.(*processorListener).run.func1                                                                                                                                                                                                                                 
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:779                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1                                                                                                                                                                                                                                        
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:155                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.BackoffUntil                                                                                                                                                                                                                                              
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:156                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.JitterUntil                                                                                                                                                                                                                                               
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:133                                                                                                                                                                                                                       
k8s.io/apimachinery/pkg/util/wait.Until                                                                                                                                                                                                                                                     
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:90                                                                                                                                                                                                                        
k8s.io/client-go/tools/cache.(*processorListener).run                                                                                                                                                                                                                                       
    /go/pkg/mod/k8s.io/client-go@v0.22.1/tools/cache/shared_informer.go:771                                                                                                                                                                                                                 
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1                                                                                                                                                                                                                                      
    /go/pkg/mod/k8s.io/apimachinery@v0.22.1/pkg/util/wait/wait.go:73
```

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Kubewarden controller has a problem when the user delete a Cluster Admission
Policy. The controller tries to update the status of the old object of the
update event which adds the delete timestamp in the resource. This fails
because the old object is not the current version of the resource, causing a
conflict and a ugly stacktrace in the logs.

To solve this, this commit rewrite the functions used to watch such events and
changes the update event handler to change status only in the new object. As
well as moves the delete handler to a separate function.

Fix #136 

## Test

See the bug [description](https://github.com/kubewarden/kubewarden-controller/issues/136#issue-1076745997). There are example of how to simulate the issue.

### CODE REVIEW

File: controllers/policies/policyserver_controller.go [hunk 1]
```diff
@@ -152,71 +192,43 @@ func (r *PolicyServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
-			if policy.DeletionTimestamp != nil {
-				// policy scheduled for deletion hence read-only, can't change
-				// status, reconcile loop removes Finalizer:
-				return []ctrl.Request{
-					{
-						NamespacedName: client.ObjectKey{
-							Name: policy.Spec.PolicyServer,
-						},
-					},
+				q.Add(watchClusterAdmissionPolicyj(r, newPolicy))
```
Comment (jvanz) [inline controllers/policies/policyserver_controller.go:206]: Can I introduce some issue just checking the new object? AFAICS in our current code there is nothing that cause issue. Let me know if I'm missing something.

File: controllers/policies/policyserver_controller.go [hunk 2]
```diff
@@ -123,6 +125,44 @@ func (r *PolicyServerReconciler) updatePolicyServerStatus(
 	)
 }
 
+// This is a function called when we detect some create or update event in a
+// ClusterAdmissionPolicy
+func watchClusterAdmissionPolicyj(reconciler *PolicyServerReconciler, object client.Object) reconcile.Request {
```
Comment (raulcabello) [inline controllers/policies/policyserver_controller.go:130]:
```suggestion
func watchClusterAdmissionPolicy(reconciler *PolicyServerReconciler, object client.Object) reconcile.Request {
```

File: controllers/policies/policyserver_controller.go [hunk 3]
```diff
@@ -152,71 +192,43 @@ func (r *PolicyServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
-				policy.Status.PolicyStatus = policiesv1alpha2.ClusterAdmissionPolicyStatusUnscheduled
-				err := r.Reconciler.UpdateAdmissionPolicyStatus(context.Background(), policy)
-				if err != nil {
-					r.Log.Error(err, "cannot update status of policy "+policy.Name)
-					return []ctrl.Request{}
+		Watches(&source.Kind{Type: &policiesv1alpha2.ClusterAdmissionPolicy{}}, handler.Funcs{
+			CreateFunc: func(e event.CreateEvent, q workqueue.RateLimitingInterface) {
+				q.Add(watchClusterAdmissionPolicyj(r, e.Object))
+			},
+			UpdateFunc: func(e event.UpdateEvent, queue workqueue.RateLimitingInterface) {
```
Comment (raulcabello) [inline controllers/policies/policyserver_controller.go:199]:
```suggestion
			UpdateFunc: func(e event.UpdateEvent, q workqueue.RateLimitingInterface) {
```

Comment (raulcabello) [reply controllers/policies/policyserver_controller.go:199]: in other places you use just `q` I don't really have a preference for `q` or `queue` but it should be the same in all funcs

**Review by raulcabello — APPROVED** [review]
LGTM! Great job! I like the approach. I just left some minor comments

**Review by raulcabello — APPROVED** [review]
LGTM, Thanks!

File: controllers/policies/policyserver_controller.go [hunk 4]
```diff
@@ -152,71 +192,43 @@ func (r *PolicyServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
 					},
-				},
-			}
-		})).
-		Complete(r)
+				})
+			},
+			GenericFunc: func(e event.GenericEvent, queue workqueue.RateLimitingInterface) {
+				queue.Add(watchClusterAdmissionPolicy(r, e.Object))
+			},
```
Comment (ereslibre) [inline controllers/policies/policyserver_controller.go:222]: Out of curiosity, what is `GenericFunc` doing here? When is it called?

File: controllers/policies/policyserver_controller.go [hunk 5]
```diff
@@ -152,71 +192,43 @@ func (r *PolicyServerReconciler) SetupWithManager(mgr ctrl.Manager) error {
...
+			CreateFunc: func(e event.CreateEvent, queue workqueue.RateLimitingInterface) {
+				queue.Add(watchClusterAdmissionPolicy(r, e.Object))
+			},
+			UpdateFunc: func(e event.UpdateEvent, queue workqueue.RateLimitingInterface) {
+				newPolicy, ok := e.ObjectNew.(*policiesv1alpha2.ClusterAdmissionPolicy)
+				if !ok {
+					r.Log.Error(err, "ObjectNew is not type of ClusterAdmissionPolicy: %#v", newPolicy)
+					queue.Add(ctrl.Request{})
+					return
 				}
```
Comment (ereslibre) [inline controllers/policies/policyserver_controller.go:205]: I find a little strange checking for the type of the object in some places before adding to the queue and not on some others, is this in purpose? Should we keep this behavior or remove this behavior and behave in the same way in all cases?

E.g. `CreateFunc` vs `UpdateFunc` vs `DeleteFunc` vs `GenericFunc` on this `handler.Funcs` instance.

**Review by ereslibre — COMMENTED** [review]
Thank you @jvanz! A couple of comments.

File: controllers/policies/policyserver_controller.go (hunk 4 above)
Comment (jvanz) [reply controllers/policies/policyserver_controller.go:222]: The `controller-runtime` [documentation](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.1/pkg/event#GenericEvent) says:

```
GenericEvent is an event where the operation type is unknown (e.g. polling or event originating outside the cluster). GenericEvent should be generated by a source.Source and transformed into a reconcile.Request by an handler.EventHandler. 
```

This is the first time that I saw a generic event as well.

File: controllers/policies/policyserver_controller.go (hunk 5 above)
Comment (jvanz) [reply controllers/policies/policyserver_controller.go:205]: No, this is not in purpose. I missed this and I'll push this changes soon.

File: controllers/policies/policyserver_controller.go (hunk 4 above)
Comment (viccuad) [reply controllers/policies/policyserver_controller.go:230]: Briefly looked on the internet and tests of controller-runtime and couldn't come up with examples of a GenericEvent. Given that they make come out of cluster, I think it's a good idea to register the function in the handler as we are doing it.
And I also like that `watchClusterAdmissionPolicy()` contains all the logic, and that the `GenericFunc` calls it, so it doesn't matter if it's a maskeraded create, update (at first I thought about moving the setting of `unscheduled` out of `watchClusterAdmissionPolicy()` and into `CreateFunc`, but I don't think it's a good idea if we keep `GenericFunc`).

File: controllers/policies/policyserver_controller.go [hunk 6]
```diff
@@ -123,6 +125,44 @@ func (r *PolicyServerReconciler) updatePolicyServerStatus(
...
+	if err != nil {
+		reconciler.Log.Error(err, "cannot list PolicyServers corresponding to policy "+policy.Name)
+		return ctrl.Request{}
+	}
+	if len(policyServers.Items) == 0 {
+		return reconciler.reconcileOrphanPolicies(policy)
+	}
+
+	policy.Status.PolicyStatus = policiesv1alpha2.ClusterAdmissionPolicyStatusPending
+	err = reconciler.Reconciler.UpdateAdmissionPolicyStatus(context.Background(), policy)
```
[the remark this answers is not in the document]
Comment (viccuad) [reply controllers/policies/policyserver_controller.go:153]: I'm happy with the current behavior. As I understand it, it first sets `unscheduled`, which triggers a new watch loop, which then goes to reconcile the the list of policy servers and orphan policies and then sets it to `pending`. Just 1 path on the finite state machine.

**Review by viccuad — APPROVED** [review]
LTGM, nice approach!

File: controllers/policies/policyserver_controller.go (hunk 6 above)
[the remark this answers is not in the document]
Comment (ereslibre) [reply controllers/policies/policyserver_controller.go:153]: I'm also fine with the current behavior after the changes.

**Review by ereslibre — COMMENTED** [review]
Thanks! Just a couple of comments from my side

File: controllers/policies/policyserver_controller.go (hunk 4 above)
Comment (raulcabello) [reply controllers/policies/policyserver_controller.go:230]: I can't find anything on the documentation. I ran a some tests, and everything seems to work fine without the `GenericFunc`. Although I'm not sure if there are some scenarios where it is called. I think we should be fine with `CreateFunc`, `UpdateFunc` and `DeleteFunc`.

Comment (jvanz) [reply controllers/policies/policyserver_controller.go:230]: FYI: One more [piece of documentation](https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.11.1/pkg/handler#EventHandler) that I found in the `controller-runtime` lib

```
	// Generic is called in response to an event of an unknown type or a synthetic event triggered as a cron or
	// external trigger request - e.g. reconcile Autoscaling, or a Webhook.
```

I'm wondering if we set the callback to `nil` may cause a crash our controller to crash in some cases. Don`t you think? Maybe we can log when we receive this kind of event.

Comment (ereslibre) [reply controllers/policies/policyserver_controller.go:230]: I think is common to see only the one that controller-runtime users care about implemented (e.g. `CreateFunc` and `DeleteFunc` only).

The logic is https://github.com/kubernetes-sigs/controller-runtime/blob/f62a0f579d73fc2ea7b0aeed597521b83f9c3966/pkg/handler/eventhandler.go#L78-L104.

In any case, if you think this is me overreacting and you folks believe is better to keep it, I'm not strictly opposing to keep it, just that makes me a little nervous implementing something that we don't know if we need it or why.

Comment (jvanz) [reply controllers/policies/policyserver_controller.go:230]: I agree that we should implement only the things that we know. Less code is better. My only concerns if we miss something. Because the previous [function forward any kind of event to our previous defined function](https://github.com/kubernetes-sigs/controller-runtime/blob/f62a0f579d73fc2ea7b0aeed597521b83f9c3966/pkg/handler/enqueue_mapped.go#L74-L77).

What I'm thinking to do is run the end-to-end tests in a version with no generic event implemented. If everything went fine, I'll remove the callback for this event type.

Comment (ereslibre) [reply controllers/policies/policyserver_controller.go:230]: Thank you @jvanz

**Review by ereslibre — APPROVED** [review]
Thank you @jvanz! LGTM
