### PR TITLE
fix: rename some consts and functions.

### LINKED ISSUE #782: Certificates package naming clean-up
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When refactoring the certificates package we spotted a few naming incongruences:

[kubewarden-controller/pkg/apis/policies/v1/policyserver_types.go](https://github.com/kubewarden/kubewarden-controller/blob/030edce6f7c57d54b88453054e39f9baa20377cc/pkg/apis/policies/v1/policyserver_types.go#L132)

Line 132 in [030edce](https://github.com/kubewarden/kubewarden-controller/commit/030edce6f7c57d54b88453054e39f9baa20377cc)
 PolicyServerCASecretReconciled PolicyServerConditionType = "CASecretReconciled" 
should be named CertSecretReconciled instead.

NOTE: check if the status name changes break something and if CRD generation is needed.

Other incongruneces were reported here:
https://github.com/kubewarden/kubewarden-controller/pull/777

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by jvanz**
## Description

Renames some functions and constants in the code related to CA and certificates reconciliation to avoid confusion.

Fix #782

### CODE REVIEW

File: internal/controller/policyserver_controller.go [hunk 1]
```diff
@@ -80,12 +80,12 @@ func (r *PolicyServerReconciler) Reconcile(ctx context.Context, req ctrl.Request
 		return r.reconcileDeletion(ctx, &policyServer, policies)
 	}
 
-	policyServerCARootSecret, err := r.fetchOrInitializePolicyServerCARootSecret(ctx, &policyServer)
+	CARootSecret, err := r.reconcileInternalCARootSecret(ctx, &policyServer)
```
Comment (fabriziosestito) [inline internal/controller/policyserver_controller.go:83]: unfortunately, we should use `caRootSecret` here since Pascal-cased local (unexported) variables are not idiomatic in go

**Review by fabriziosestito — APPROVED** [review]
Thanks for this, looks very clean now.

Just one small comment added, we can merge once addressed

**Review by viccuad — APPROVED** [review]
LGTM modulo Fabrizio's comment.
